# Jekyll template created by LorenzoPegorari
# The "academicpages" theme was used as a reference (https://github.com/academicpages/academicpages.github.io)

# Basic site settings
lang        : "en-US"
title       : "oss-contributions-archive"
author      : "Lorenzo Pegorari"
description : "Archive of all the contibutions that I've made to OSS organizations."
url         : https://lorenzopegorari.github.io  # the base hostname & protocol for your site e.g. "https://[your GitHub username].github.io" or if you already have some other page hosted on Github then use "https://[your GitHub username].github.io/[Your Repo Name]"
baseurl     : "/oss-contributions-archive"  # the subpath of your site, e.g. "/blog"
header      : "OSS Contributions Archive"  # Text for header
